package com.ltalk.enums;

public enum ProtocolType {
    CHAT, SIGNUP, LOGIN, CHAT_LIST, DISCONNECT, REQUEST_FRIEND, CREATE_CHATROOM,
    NEW_CHAT, READ_CHAT, GET_VOICE_SERVER_IP, JOIN_VOICE_CHAT, RESPONSE_CREATE_CHATROOM_MEMBER,
    FRIEND_SEARCH, CAN_CREATE_CHAT_ROOM;

}
